name: Java Compile

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  code-style:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run code-style
        run: java -jar code-style/checkstyle-10.23.0-all.jar -c code-style/checkstyle.xml src/

  compile:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Compile maven project
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run maven tests
        run: mvn test

  build:
    runs-on: ubuntu-latest
    needs: [ test, code-style ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Pom.xml with Maven
        run: |
          mvn -B package --file pom.xml
          echo "Built files in target directory:"
          ls -l target/

      - name: Rename JAR file
        run: |
          echo "Looking for JAR files:"
          find target -name "*.jar"
          cp target/jabberpoint-1.0.0-SNAPSHOT.jar JabberPoint.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: jabberpoint-jar
          path: JabberPoint.jar

  create_release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          # Get the latest tag, default to v1.7.0 if none exists
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$latest_tag" ]; then
            latest_tag="v1.7.0"
          fi
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "Latest Tag: $latest_tag"

      - name: Create New Version
        id: generate_version
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          if [ -z "$patch" ]; then
            new_version="v1.7.0"
          else
            new_patch=$((patch + 1))
            new_version="v$major.$minor.$new_patch"
          fi
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "Generated new version: $new_version"

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jabberpoint-jar

      - name: Verify JAR file
        run: |
          echo "Current directory contents:"
          ls -la
          echo "JAR file details:"
          file JabberPoint.jar || true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.generate_version.outputs.new_version }}
          name: Release ${{ steps.generate_version.outputs.new_version }}
          files: JabberPoint.jar
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}