name: Java Compile

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Compile Java files
        run: |
          mkdir -p bin
          find src/main/java -name "*.java" > sources.txt
          javac -d bin @sources.txt

      - name: Compile project
        run: mvn compile
