name: Java Compile

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  code-style:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run code-style
        run: java -jar code-style/checkstyle-10.23.0-all.jar -c code-style/checkstyle.xml src/

  compile:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Compile maven project
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run maven tests
        run: mvn test
